# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-mongo
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 200G
#   accessModes:
#     - ReadWriteOnce
#   claimRef:
#     namespace: default
#     name: pvc-mongo
#   gcePersistentDisk:
#     pdName: gke-mongo-disk
#     fsType: ext4
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: failure-domain.beta.kubernetes.io/zone
#               operator: In
#               values:
#                 - us-east1-c
#             - key: failure-domain.beta.kubernetes.io/region
#               operator: In
#               values:
#               - us-east1
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-mongo
# spec:
#   storageClassName: ""
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 200G

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
spec:
  storageClassName: slow
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08c06cd7ca5d25288
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: default
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
