apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
spec:
  storageClassName: slow
  capacity:
    storage: 20G
  accessModes:
    - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-08c06cd7ca5d25288
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: default
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20G
