apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-strapi
spec:
  storageClassName: standard
  capacity:
    storage: 50G
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: pvc-strapi
  gcePersistentDisk:
    pdName: test-1-300600-gke-1
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
                - us-east1-c
            - key: failure-domain.beta.kubernetes.io/region
              operator: In
              values:
              - us-east1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-strapi
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50G

